// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hand; mirrors the shape mdatagen would produce.
// See metadata.yaml for the component definition this describes.

package metadata // import "github.com/ucpr/opentelemetry-collector-components/exporters/notificationexporter/internal/metadata"

import "go.opentelemetry.io/collector/component"

var Type = component.MustNewType("notification")

const (
	LogsStability = component.StabilityLevelDevelopment
)
