name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # ratchet:actions/checkout@v4.4.0

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # ratchet:actions/setup-go@v5.6.0
        with:
          go-version-file: go.work

      - name: go build
        run: |
          for mod in $(go list -m -f '{{if not .Version}}{{.Dir}}{{end}}' all); do
            echo "::group::go build ($mod)"
            (cd "$mod" && go build ./...)
            echo "::endgroup::"
          done

      - name: go vet
        run: |
          for mod in $(go list -m -f '{{if not .Version}}{{.Dir}}{{end}}' all); do
            echo "::group::go vet ($mod)"
            (cd "$mod" && go vet ./...)
            echo "::endgroup::"
          done

      - name: go test
        run: |
          for mod in $(go list -m -f '{{if not .Version}}{{.Dir}}{{end}}' all); do
            echo "::group::go test ($mod)"
            (cd "$mod" && go test ./... -v)
            echo "::endgroup::"
          done
