name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work

      - name: go build
        run: |
          for mod in $(go list -m -f '{{if not .Version}}{{.Dir}}{{end}}' all); do
            echo "::group::go build ($mod)"
            (cd "$mod" && go build ./...)
            echo "::endgroup::"
          done

      - name: go vet
        run: |
          for mod in $(go list -m -f '{{if not .Version}}{{.Dir}}{{end}}' all); do
            echo "::group::go vet ($mod)"
            (cd "$mod" && go vet ./...)
            echo "::endgroup::"
          done

      - name: go test
        run: |
          for mod in $(go list -m -f '{{if not .Version}}{{.Dir}}{{end}}' all); do
            echo "::group::go test ($mod)"
            (cd "$mod" && go test ./... -v)
            echo "::endgroup::"
          done
